[build]
  command = "flutter build web --release"
  publish = "build/web"

[[plugins]]
  package = "netlify-plugin-flutter"
    [plugins.inputs]
      channel = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
