[build]
  command = '''
    export PATH="$PATH":"$HOME/.pub-cache/bin" \
    && export MELOS_SDK_PATH=~/flutter \
    && dart pub global activate melos \
    && melos bootstrap \
    && melos run build:web
  '''
  publish = "build/web"

[[plugins]]
  package = "netlify-plugin-flutter"
    [plugins.inputs]
      channel = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
