name: habit_quokka
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  adaptive_theme: ^3.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_sorter:
  comments: false
