name: habitquokka
description: Build better habits, one window at a time
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: 3.1.3
  flutter: 3.13.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  adaptive_theme: ^3.4.1
  flutter_adaptive_scaffold: ^0.1.7+1
  go_router: ^11.1.2
  responsive_builder: ^0.7.0
  animated_emoji: ^2.0.0
  google_fonts: ^6.1.0
  url_strategy: ^0.2.0
  preload_page_view: ^0.2.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  reactive_forms: ^16.1.0
  reactive_forms_annotations: ^4.2.0
  murmur3: ^2.1.0
  supabase_flutter: ^1.10.21
  async_redux: ^20.0.2
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
  json_annotation: ^4.8.1
  material_color_utilities: ^0.5.0
  flutter_svg: ^2.0.7
  flutter_markdown: ^0.6.18

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^2.0.3
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  melos: ^3.1.1
  reactive_forms_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Lilita_One/
    - assets/fonts/Noto_Sans/
    - assets/licenses/noto-animated-emoji-cc-by-40.txt
    - assets/logo.svg
    - assets/terms.md
    - assets/policy.md
    - assets/help.md

import_sorter:
  comments: false
