name: habitquokka
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: 3.0.3
  flutter: 3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  adaptive_theme: ^3.3.0
  flutter_adaptive_scaffold: ^0.1.4
  go_router: ^7.1.1
  responsive_builder: ^0.7.0
  animated_emoji: ^2.0.0
  google_fonts: ^4.0.4
  url_strategy: ^0.2.0
  preload_page_view: ^0.2.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  reactive_forms: ^14.3.0
  reactive_forms_annotations: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  melos: ^3.1.0
  reactive_forms_generator: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Lilita_One/
    - assets/fonts/Noto_Sans/

import_sorter:
  comments: false
