name: habitquokka
description: Build better habits, one window at a time
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: 3.4.0
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  adaptive_theme: ^3.6.0
  flutter_adaptive_scaffold: ^0.1.10+2
  go_router: ^14.1.3
  responsive_builder: ^0.7.0
  animated_emoji: ^3.1.0
  google_fonts: ^6.2.1
  url_strategy: ^0.2.0
  preload_page_view: ^0.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^5.0.0
  murmur3: ^2.1.0
  supabase_flutter: ^2.5.3
  async_redux: ^23.0.2
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
  json_annotation: ^4.9.0
  material_color_utilities: ^0.8.0
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.10
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.8.0
  melos: ^6.0.0
  reactive_forms_generator: ^5.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Lilita_One/
    - assets/fonts/Noto_Sans/
    - assets/licenses/noto-animated-emoji-cc-by-40.txt
    - assets/logo.svg
    - assets/terms.md
    - assets/policy.md
    - assets/help.md

import_sorter:
  comments: false
